# Generated by Django 3.0.5 on 2023-07-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosheilah', '0004_people_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.IntegerField(default=1),
        ),
    ]
