# Generated by Django 3.0.5 on 2023-07-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosheilah', '0006_auto_20230728_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='country',
            field=models.CharField(default='Kenya', max_length=30),
        ),
    ]
