# Generated by Django 3.0.5 on 2023-07-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosheilah', '0007_auto_20230728_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='people',
            name='country',
            field=models.CharField(max_length=30),
        ),
    ]
