# Generated by Django 3.0.5 on 2023-07-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosheilah', '0008_auto_20230731_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='city',
            field=models.CharField(default='Nairobi', max_length=30),
        ),
        migrations.AlterField(
            model_name='people',
            name='country',
            field=models.CharField(default='Kenya', max_length=30),
        ),
    ]
